### PR TITLE
Add PHPStan 

### PR DESCRIPTION
**Pull request by WendellAdriel**
Hey @erikaheidi I'm creating this PR for an initial configuration for PHPStan.
I added it and fixed the issues until Level 5 because starting on Level 6 there are some more issues to fix and I don't have the time to go over all of them now, but if this PR is merged I'll be working on other PRs to increase the level

### CODE REVIEW

**Comment by WendellAdriel** [comment]
Also, if this gets merged, I'll send another PR adding the PHPStan check to the GitHub Actions if you want to.

**Comment by JustSteveKing** [comment]
This was on my list of things to add!

**Comment by WendellAdriel** [comment]
Nice, @JustSteveKing!
Thanks for merging it!
I’ll be working on new PRs to level up the PHPStan config! 😉

**Comment by JustSteveKing** [comment]
> Nice, @JustSteveKing!
> Thanks for merging it!
> I’ll be working on new PRs to level up the PHPStan config! 😉 

I am 100% up for this! I'd like to also introduce more generics if possible to make the experience of using Minicli feel more sleek

**Pull request merged**
