### PR TITLE
Add php-cs-fixer process in the pipeline

### PR DESCRIPTION
**Pull request by ScullWM**
- Add php-cs in the CI pipeline
- Clean php code

### CODE REVIEW

**Comment by lotfio** [comment]
up vote for cs-fixer 👍

**Comment by erikaheidi** [comment]
This is looking good, thank you for the contribution! Looking forward to merging it. Let me know when it's ready (since the PR title says it's a WIP).

**Comment by ScullWM** [comment]
Yes, look like the GA worked like a charm on the first try. I remove the WIP label 👌

**Comment by syntaxseed** [comment]
> Being the "devil's advocate": can you use some default pattern, like PSR-12 or Symfony, instead of create a new pattern with config?

I agree with this. I had a hard time parsing what the config was was getting at. I think covering at least PSR 1 & 2 and whatever else makes sense would be more clear.

My own projects use:

```
php-cs-fixer fix . --rules=full_opening_tag,no_closing_tag,@PSR1,@PSR2
```

**Comment by ScullWM** [comment]
yes @wandersonwhcr and @syntaxseed I agree with you.
Lets use "default pattern" and add stricter convention depending our requirement. (I've update the MR)

**Comment by erikaheidi** [comment]
This looks great, thank you for the PR @ScullWM ! Also thanks for the quick response after everyone's input. Merging this now :+1:

**Pull request merged**
