### PR TITLE
Allow themes to override ColorOutputFilter

### PR DESCRIPTION
**Pull request by cutepetric**
I would like to be able to disable all colours when redirecting output to a log file, for example:

Eg:
$app = new App([
    'theme' => stream_isatty(STDOUT) ? 'App\Theme\Default' : '\Raw',
]);

### CODE REVIEW

**Comment by JustSteveKing** [comment]
Hey @cutepetric - are you still interested in this PR moving forward?

**Comment by cutepetric** [comment]
Yes, of course, it was a useful feature for my use-case.

**Comment by JustSteveKing** [comment]
@cutepetric leave it with me to have a look and we can work on getting this merged

**Review by JustSteveKing — APPROVED** [review]
This will work well for what we need right now, but we can revisit the theming options later on

**Pull request merged**
