### PR TITLE
merge V2.2

### PR DESCRIPTION
**Pull request by JustSteveKing**

### CODE REVIEW

**Comment by erikaheidi** [comment]
Hey guys, I think there are some changes in the latest PR from @WendellAdriel that break this code, it has some merge conflicts. Can you check this when you have some time, @JustSteveKing ?

**Comment by JustSteveKing** [comment]
> Hey guys, I think there are some changes in the latest PR from @WendellAdriel that may break these changes, it has some merge conflicts. Can you check this when you have some time, @JustSteveKing ?

No problems @erikaheidi - leave it with me :smile:

**Comment by JustSteveKing** [comment]
@WendellAdriel let's work on this before we get too far ahead with other things

**Comment by WendellAdriel** [comment]
@JustSteveKing sure, do you want me to create a PR to the v2.2 branch to comply with my latest changes?

**Comment by JustSteveKing** [comment]
> @JustSteveKing sure, do you want me to create a PR to the v2.2 branch to comply with my latest changes?

That would be great 🙂

**Comment by WendellAdriel** [comment]
@JustSteveKing the PR I opened is to merge the changes into the v2.2, so it will fix the conflicts on this PR. No need to close this one, when the other one gets merged this one can be merged to main to have a better visibility on the changes that will be merged

**Comment by erikaheidi** [comment]
This seems fairly outdated, so I'm closing the PR. Please open a new PR based on latest `main` if something is still missing.

**Pull request closed without merging**
