### PR TITLE
register multiple commands

### PR DESCRIPTION
**Pull request by tal7aouy**
This is a method named `registerCommands` that allows to register many commands instead of one command.
```
 /**
     * @param array<string, callable> $commands
     * @return void
     */
    public function registerCommands(array $commands): void
    {
        foreach ($commands as $name => $callable) {
            $this->registerCommand($name, $callable);
        }
    }
```

### CODE REVIEW

**Review by WendellAdriel — CHANGES_REQUESTED** [review]
Some checks are failing, but besides that, I think that's all good! 💪

**Comment by tal7aouy** [comment]
Yeah you're right i forgot to lint the using pint

**Review by erikaheidi — APPROVED** [review]

**Comment by WendellAdriel** [comment]
Thanks for the contribution @tal7aouy 🔥

**Comment by tal7aouy** [comment]
Happy to contribute :100:

**Pull request merged**
