### PR TITLE
Static analysis

### PR DESCRIPTION
**Pull request by JustSteveKing**
This branch ups the PHPStan level to level 9 🔥 

I had to use two `@phpstan-ignore-next-line` on the `fopen` functions, as I cannot cast or guarantee anything is a resource without changing functionality too much. This is a compromise I am happy to make for now, until more reactors are planned.

### CODE REVIEW

**Comment by JustSteveKing** [comment]
@WendellAdriel here we go 🔥

**Comment by WendellAdriel** [comment]
> @WendellAdriel here we go 🔥

That's what I'm talking about!!!
I had created this one #67, but this beats mine hahahahaha
Way to go, man!!! 🔥 💪

**Comment by WendellAdriel** [comment]
@JustSteveKing In my PR I worked on the `checkMissingIterableValueType` rule
After you merge this PR, can I create a new PR with only these changes so we can remove this from the PHPStan config file to check for this rule as well?

**Comment by JustSteveKing** [comment]
> @JustSteveKing In my PR I worked on the `checkMissingIterableValueType` rule
> After you merge this PR, can I create a new PR with only these changes so we can remove this from the PHPStan config file to check for this rule as well?

That sounds like a great idea!

**Comment by WendellAdriel** [comment]
> That sounds like a great idea!

I'll do that, then.
Thanks man! 💪

**Review by erikaheidi — APPROVED** [review]

**Pull request merged**
