### PR TITLE
change path of shebang

### PR DESCRIPTION
**Pull request by flug**

### CODE REVIEW

**Comment by lotfio** [comment]
@erikaheidi This is useful it will help to automatically resolve the php interpreter in envireonments like `mingw` `msys` (and even linux and mac if the instalation of php doesn't follow the default instalation (custom user instalation)).

example of the error that this pull fix:

bad-interpreter

@flug  Thanks for the pull 👍

**Comment by syntaxseed** [comment]
Will this prevent it from working on standard systems?

**Comment by lotfio** [comment]
@syntaxseed nope ! it will work fine :)

**Comment by flug** [comment]
https://github.com/symfony/symfony-standard/blob/3.4/bin/console#L1

**Comment by erikaheidi** [comment]
Looking good, thank you for the PR @flug and thank you for the explanation @lotfio :) 

:dancers: merging now!

**Pull request merged**
