### PR TITLE
Fix conflicts with V2.2

### PR DESCRIPTION
**Pull request by WendellAdriel**
@JustSteveKing @erikaheidi I think I may have done something wrong here because I'm seeing a lot of changes and commits 😅

### CODE REVIEW

**Comment by JustSteveKing** [comment]
Yeah you want to make sure you work against the main branch as your source of truth @WendellAdriel 🙂

**Comment by WendellAdriel** [comment]
I created a branch from 2.2, then I merged the main on it and fixed the conflicts, @JustSteveKing is this the expected?

**Comment by JustSteveKing** [comment]
I'm pretty sure the 2.2 branch is the last major version? Let me have a look at the PR changes :smile:

**Comment by WendellAdriel** [comment]
Thanks, @JustSteveKing if I need to change anything just let me know!

**Comment by erikaheidi** [comment]
This looks it needs a rebase, or maybe it's easier to just move the changes to a clean cloned repo and submit a new PR, @WendellAdriel

**Comment by WendellAdriel** [comment]
> This looks like it needs a rebase, or maybe it's easier to just move the changes to a clean cloned repo and submit a new PR, @WendellAdriel

I think it's easier to move the changes, I'm going to create a new branch from main and move the changes to there and create a new PR then, so I'm closing this one for now

**Pull request closed without merging**
