### PR TITLE
PHPStan improvements

### PR DESCRIPTION
**Pull request by WendellAdriel**
This is a follow-up of #67 and #68

In this PR I update the PHPStan config to check the two rules that it was ignoring and apply the fixes for them.

### CODE REVIEW

**Comment by WendellAdriel** [comment]
Here we go, @JustSteveKing!!! 🔥

**Comment by erikaheidi** [comment]
I'll leave this one for the king @JustSteveKing :)

**Review by JustSteveKing — APPROVED** [review]
Fantastic additions and improvements - nice job @WendellAdriel 🔥

**Comment by WendellAdriel** [comment]
> Fantastic additions and improvements - nice job @WendellAdriel 🔥

Thank you so much, @JustSteveKing!!! 💪

**Pull request merged**
